### ISSUE TITLE
License and home

### ISSUE THREAD

**Issue by fedorov** [pieper/dcmjs#1]
Is there a particular reason why this repo is under Slicer license? Maybe switch to Apache or something, while it is early in the process? (e.g, cornerstone is MIT https://github.com/chafey/cornerstone/blob/master/LICENSE).

How about moving (not forking!) this repository under QIICR organization, or OHIF organization?

**Comment by pieper** [comment]
The license was changed to MIT yesterday.

This is in my repo because we didn't know for sure which org would want to take responsibility and didn't want to wait while we hashed that out.  If we are happy with this as a QIICR deliverable then I think that's the best home for now, but longer term OHIF might be better (see why we didn't want to delay?) 😄

**Comment by fedorov** [comment]
> The license was changed to MIT yesterday.

Ah, I didn't even think to re-check. 👍 

> we didn't know for sure which org would want to take responsibility

I think responsibility will always lie with the individuals who are interested to contribute and maintain a repo. Organization is a means to organize and provide some consistency, continuity and common theme to the development. It can also help with the visibility. I am fine with either QIICR or OHIF - you guys are the authors, so you decide. It is not like there is a contract that every repo under every organization is expected to meet certain maintenance criteria.

If this development is supported by QIICR though, would be appropriate to add an acknowledgment, whatever is the decision about the home.

**Comment by pieper** [comment]
Agreed - there needs to be a README.  I'll add that.
